{{- if .Values.azure.keyVaultCsi }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.serviceAccount.name }}-spc
  namespace: {{ .Release.Namespace }}
  labels: {{- include "petclinic.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.azure.workloadIdentityClientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: petclinic-db-username
          objectType: secret
        - |
          objectName: petclinic-db-password
          objectType: secret
  secretObjects:
    - secretName: {{ .Values.database.existingSecret }}
      type: Opaque
      data:
        - objectName: petclinic-db-username
          key: {{ .Values.database.usernameKey }}
        - objectName: petclinic-db-password
          key: {{ .Values.database.passwordKey }}
{{- end }}
