{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "petclinic.labels" . | nindent 4 }}
  {{- if .Values.azure.workloadIdentityClientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentityClientId | quote }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
