# template only - the demo secret is created by scripts/03-deploy-app.sh; on AKS it comes from
apiVersion: v1
kind: Secret
metadata:
  name: demo-db
  namespace: petclinic
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: petclinic
type: Opaque
stringData:
  username: "REPLACE_ME"
  password: "REPLACE_ME"
  database: "petclinic"
