apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: petclinic
  labels:
    app.kubernetes.io/name: petclinic
    app.kubernetes.io/part-of: petclinic
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: petclinic
  ports:
    - name: http
      port: 80
      targetPort: http
